version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5772:5672"

  carservice:
    image: clean-car-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-service-app
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq