name: Java CI with Maven

on: [push,pull_request]

jobs:
  build:

    runs-on: maven:3.8.4-eclipse-temurin-17-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Unit Test
      run: mvn -B clean test --file pom.xml
